#!/usr/bin/env bash
# Bash script that will display information about subdomains.
# $1 [SUB_DOMAIN]
# $2 [RECORD_TYPE]

domain_infoDisplay() {
	#funtion that displays info of a/all subdomain(s)

	domain=$1
	subdomain=$2
	hostname="$subdomain.$domain"

	recordType=$(dig "$hostname" | grep -A1 'ANSWER SECTION:' | tail -1 |awk '{print $4}')
	ipAdd=$(dig "$hostname" | grep -A1 'ANSWER SECTION:' | tail -1 |awk '{print $5}')


echo "The subdomain $subdomain is a $recordType record and points to $ipAdd"
}

if [ $# -eq 1 ]; then
	subdomains=( "www" "lb-01" "web-01" "web-02")
	for subd in "${subdomains[@]}"; do
		domain_infoDisplay "$1" "$subd"
	done

elif [ $# -eq 2 ]; then
	domain_infoDisplay "$1" "$2"
fi
