#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt -y update

sudo apt install -y nginx

# Create index.html with "Hello World!" message
#echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Configure redirection
sudo sed -i '/location \/ {/a \    location \/redirect_me {\n        return 301 http:\/\/ovagames.com;\n    }' /etc/nginx/sites-available/default

if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi
