#!/usr/bin/env bash
#Bash script

echo $$ > /var/run/myscript.pid
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit' SIGTERM
	trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT
	trap 'echo "Y U no love me?!"' SIGINT
done
