#!/usr/bin/env bash
#101-tell_the_story_of_passwd

File="/etc/passwd"
while IFS=: read -r user passwd uid gid name home shell
do
	printf "The user %s is part of the %s gang, lives in %s " "$user" "$gid" "$home"
	printf "and rides %s. %s's place is protected by the passcode %s, " "$shell" "$uid" "$passwd"
	printf "more info about the user here: %s" "$name"
	printf "\n"
done < $File
