#!/usr/bin/env bash

#use of while loop and if statements

incr=0
while [ $incr -lt 10 ]
do
	if [ $incr -eq 3 ]
	then
		echo "bad luck"
	elif [ $incr -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((incr++))
done
