#!/usr/bin/env bash
# Bash script that gives information about the school file.

filen=school
if [ -e $filen ]; then
	echo "$filen file exists"

	if [ -s $filen ]; then
		echo "$filen file is not empty"
	else
		echo "$filen file is empty"
	fi

	if [ -f $filen ]; then
		echo "$filen is a regular file"
	fi
else
	echo "$filen file does not exist"
fi

