#!/usr/bin/env bash
# script that configures the following:
# 1 nginx must be running as nginx user
# 2 nginx must be listening on all active IPs on port 8080

sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i '15i\user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
